### PR TITLE
Scrape all

### PR DESCRIPTION
**Pull request by kacperadach**
for me to just run the scrape.py script and get all the csvs I need to add to [dk_files](https://github.com/kacperadach/dk_files)

### CODE REVIEW

**Comment by kacperadach** [comment]
I dont know why the tests are failing, any idea?

**Comment by BenBrostoff** [comment]
@kacperadach Think this is related to how the Dockerfile is written (notice how the error is `No module named dk`)  - the working directory it creates is called `dk` (and the tests run in a Docker container on Travis). You could try changing the Dockerfile to name the repo `draft_kings_fun`.

**Comment by BenBrostoff** [comment]
@kacperadach I think this one is annoying because I named this repo `draft-kings-fun` - I never considered using it as a submodule at the time I made it. We have a couple options - check out this [S/O thread for how to import a module under a directory with dashes](http://stackoverflow.com/questions/11655490/python-module-resides-in-a-repository-whose-name-contains-dash-characters).

If you want to make these changes, I'm fine with merging them (I don't want to change the name of the repo at this point).  If you don't, we can keep using that one branch for submodule use.

**Comment by BenBrostoff** [comment]
Closing because of all the issues we discussed / this is way behind master now. Definitely down to revisit at later point in time.

**Pull request closed without merging**
