### PR TITLE
I didn't check my work, the missing tr is for fanpros

### PR DESCRIPTION
**Pull request by kacperadach**
I messed up, didn't check my work, I will never succeed. The changed html element was for fanpros

### CODE REVIEW

**Comment by kacperadach** [comment]
proof

**Comment by BenBrostoff** [comment]
https://www.youtube.com/watch?v=DzGV06OKZTk

**Comment by BenBrostoff** [comment]
Nice, this works and I'll merge. Love that naming of the branch.

**Comment by kacperadach** [comment]
This was a typical Ryan Mallet move

**Pull request merged**
