### PR TITLE
small orm change

### PR DESCRIPTION
**Pull request by kacperadach**
just moved repr to after init to group built-in methods and added a method that checks if two rosters are identical

### CODE REVIEW

**Comment by BenBrostoff** [comment]
Power play request alert - can you write a test for this one? Should be pretty easy in `tests.py` / you can run the tests via `nosetests`.

**Comment by kacperadach** [comment]
Right away boss!

**Comment by BenBrostoff** [comment]
Get ready for another you're going to hate me comment - is it possible for you to just overwrite the `__eq__` built-in method? That way you can literally do `roster_1` == `roster_2` instead of calling a named method.

**Comment by BenBrostoff** [comment]
[Also I nominate this as the official video of "I hate this code review comment."](https://www.youtube.com/watch?v=2Q-Y2gTBM4I).

**Comment by kacperadach** [comment]
nah that makes perfect sense, didnt know that was a built in

**Comment by kacperadach** [comment]
Love the school of Brostoff

**Comment by BenBrostoff** [comment]
@kacperadach you the man
image

**Pull request merged**
